---
# This role installs httpd

- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - libsemanage-python
   - libselinux-python

- name: http service state
  service: name=httpd state=started enabled=yes
